import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import M_Header from "./component/m_header/m_header";
import M_Heder_BG from "./component/m_header/m_header_bg";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <M_Header site_title="My WebSite2024" />
        <M_Heder_BG />
        {children}
      </body>
    </html>
  );
}
